CmakeTest16

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -27,21 +27,6 @@ env:
   BUILD_DIR: "build"
 
 jobs:
-  cppcheck:
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Install cppcheck
-        run: |
-          sudo apt update
-          sudo apt install -y cppcheck
-
-      - name: Run cppcheck
-        run: |
-          cppcheck --enable=all --inconclusive --std=c++20 --quiet src/ generated/src/
-
   build:
     runs-on: ${{ matrix.os }}
     strategy:
@@ -61,9 +46,14 @@ jobs:
             sudo apt update
             sudo apt install -y libopencv-dev libsfml-dev cmake g++
           elif [[ ${{ matrix.os }} == 'macos-14' ]]; then
+            if ! command -v brew &> /dev/null; then
+              echo "Homebrew not found. Installing..."
+              /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+            fi
             brew install opencv sfml cmake llvm
           elif [[ ${{ matrix.os }} == 'windows-2022' ]]; then
             choco install opencv llvm cmake mingw
+          fi
 
       - name: Configure CMake
         run: |
@@ -80,58 +70,3 @@ jobs:
         run: |
           cd build
           ctest --output-on-failure
-
-  clang-tidy:
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Install clang-tidy
-        run: |
-          sudo apt update
-          sudo apt install -y clang-tidy
-
-      - name: Verify src Directory Exists
-        run: |
-          if [ ! -d "src" ]; then
-            echo "Error: src directory does not exist. Skipping Clang-Tidy.";
-            exit 0;
-          fi
-
-      - name: Run clang-tidy
-        run: |
-          clang-tidy src/*.cpp -- -std=c++20
-
-  clang-tidy-macos-windows:
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [macos-14, windows-2022]
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-
-      - name: Install clang-tidy dependencies
-        run: |
-          if [[ "${{ matrix.os }}" == 'macos-14' ]]; then
-            if ! command -v clang-tidy &> /dev/null; then
-              brew install llvm
-            fi
-          elif [[ "${{ matrix.os }}" == 'windows-2022' ]]; then
-            if ! command -v clang-tidy &> /dev/null; then
-              choco install llvm
-            fi
-          fi
-
-      - name: Verify src Directory Exists
-        run: |
-          if [ ! -d "src" ]; then
-            echo "Error: src directory does not exist. Skipping Clang-Tidy.";
-            exit 0;
-          fi
-
-      - name: Run clang-tidy
-        run: |
-          clang-tidy src/*.cpp -- -std=c++20
